import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.sass";
import {HomePage} from "@/src/components/home/home-page";;
const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    < div className={`${styles.main} ${inter.className}`}>
      
      <Head>
        <title>Events 2 App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data}/>

    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
